site_name: Kalyan Jewellers
site_url: https://kalyanjewellers.example.com
site_description: Premium Jewelry and Diamonds since 1985
site_author: Kalyan Jewellers

theme:
  name: material
  custom_dir: docs/overrides


  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.highlight

  font:
    text: Merriweather Sans
    code: Red Hat Mono

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  logo: assets/images/kalyan_logo.png
  favicon: assets/images/KALYANkj.png


extra_css:
  - assets/stylesheets/extra.css
  - stylesheets/extra.css
extra_javascript:
  - javascripts/custom.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js  # Local initialization (create this file)


markdown_extensions:
  - attr_list
  - pymdownx.emoji
  - pymdownx.highlight
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - blog:
      blog_dir: blog
      pagination_dir: page
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
      timezone: Asia/Kolkata  # Change to your timezone
      locale: en
  - macros
  - glightbox

nav:
  - Home: index.md
  - About Us:
    - Our Heritage: about/heritage.md
    - Craftsmanship: about/craftsmanship.md
  - Collections:
    - Gold Jewelry: collections/gold.md
    - Diamond Collections: collections/diamonds.md
    - Bridal Jewelry: collections/bridal.md
  - Services:
    - Custom Design: services/custom.md
    - Jewelry Repair: services/repair.md
  - Blog:
    - Latest Trends: blog/trends.md
  - Contact Us: contact.md


