site_name: Kalyan-Jewellers
site_url: https://sitename.example
theme :
    name : material
    favicon: assets/download.png
    logo: assets/kalyan_logo.png
    custom_dir: docs/overrides
    font:
      text: Merriweather Sans
      code: Red Hat Mono
  

    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.instant
      - navigation.indexes
      - navigation.expand
      - navigation.footer
      - search.highlight
      - search.share
      - search.suggest
      - navigation.top
      - toc.integrate

    
    palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
 



extra:
  
  generator: false




plugins:
  - search
  - blog
  

nav:
    - Kalyan Jewellers: index.md
    - About Us: ABOUT US.md
    - Services:
        - Admonitions: services/admonitions.md
        - App: services/app.md
        - Web: services/web.md
    - Team: team.md
    - Diagrams: diagram-examples.md
    - Contact: contact.md
    - Blog:
      - Overview: blog/index.md
      - "First Post": blog/2025-03-25-first-post.md
      - "Second post": blog/2025-03-26-second-post.md
    

extra_css:
  - assets/extra.css


