site_name: Kalyan Jewellers
site_url: https://kalyanjewellers.example.com
site_author:  "Manyam vandana"
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/git-alt
 

  features:
   
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.highlight
    - header.autohide
    - navigation.instant

  

  font:
    text: Merriweather Sans
    code: Red Hat Mono

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  logo: assets/images/kalyan_logo.png
  favicon: assets/images/KALYANkj.png


extra_css:
  - assets/stylesheets/extra.css
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css

extra_javascript:

  - javascripts/mermaid-init.js  
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js/

  
  - https://unpkg.com/force-image-reload@1.0.0
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/js/all.min.js





markdown_extensions:
  - attr_list
  - pymdownx.emoji
  - pymdownx.highlight
  - md_in_html
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  
plugins:
  - search
  - blog
  - macros:
      module_name: docs/main
  - glightbox
  - minify:
      minify_html: true
  
     

extra:
  mermaid:
    theme: 
      base: 
        primaryColor: "#f5f5f5"
        primaryBorderColor: "#2e86de"
        lineColor: "#2e86de"
        primaryTextColor: "#333"
    flowchart:
      diagramPadding: 20
      useMaxWidth: false
    fontSize: 16px

  


nav:
  - Kalyan Jewellers: index.md
  - About Us:
      - Our Heritage: about/heritage.md
      - Craftsmanship: about/craftsmanship.md
  - Collections:
      - Gold Jewelry: collections/gold.md
      - Diamond Collections: collections/diamonds.md
      - Bridal Jewelry: collections/bridal.md
  - Services:
      - Custom Design: services/custom.md
      - Jewelry Repair: services/repair.md
  - Blog:
      - Blog: blog/index.md
  - Contact Us: contact.md

