name: ci

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: windows-latest  # Change from ubuntu-latest to windows-latest
    
    steps:
      # Checkout code
      - uses: actions/checkout@v4
      
      # Configure Git Credentials
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # Set cache key and set environment variables (Windows compatibility for date command)
      - run: |
          echo "cache_id=$(powershell -Command "(Get-Date).ToString('yyyyMMddHHmmss')" )" >> $env:GITHUB_ENV

      # Cache dependencies (MkDocs Material)
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      # Install MkDocs Material
      - run: pip install mkdocs-material

      # Deploy using MkDocs
      - run: mkdocs gh-deploy --force
